### ISSUE TITLE
Link custom plugin to NCrystal in Mac (OSX-arm64)

### ISSUE THREAD

**Issue by XuShuqi7** [mctools/ncrystal#211]
I tried to attach a custom plugin "https://github.com/XuShuqi7/ncplugin-CrysExtn" to NCrystal in my Mac (OSX-arm64), while I find some issues. After installing NCrystal, the commands I used are:

```
git clone https://github.com/XuShuqi7/ncplugin-CrysExtn.git
cmake -S ./ncplugin-CrysExtn -B ./tmpbld -DNCPLUGIN_DEVMODE=OFF -DCMAKE_INSTALL_PREFIX=./CrysExtn_inst/
cmake --build tmpbld
cmake --install tmpbld
export NCRYSTAL_PLUGIN_LIST="$PWD/CrysExtn_inst/lib/libNCPlugin_CrysExtn.dylib"
```

When I typed ```nctool --plugin```, I got 

```
Traceback (most recent call last):
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/bin/nctool", line 1037, in <module>
    main()
    ~~~~^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/bin/nctool", line 913, in main
    NC.browsePlugins(dump=True)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/plugins.py", line 41, in browsePlugins
    l=_get_raw_cfcts()['ncrystal_get_pluginlist']()
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/_chooks.py", line 789, in ncrystal_get_pluginlist
    _raw_getpluginlist(n,ctypes.byref(l))
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/_chooks.py", line 203, in fcte
    _raise_err()
    ~~~~~~~~~~^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/_chooks.py", line 175, in _raise_err
    raise e
NCrystal.exceptions.NCDataLoadError: Could not load shared library: /Users/shuqixu/Downloads/My_C++/ncrystal_test_plugin/CrysExtn_inst/lib/libNCPlugin_CrysExtn.dylib (error was: dlopen(/Users/shuqixu/Downloads/My_C++/ncrystal_test_plugin/CrysExtn_inst/lib/libNCPlugin_CrysExtn.dylib, 0x0006): weak-def symbol not found '__ZNK8NCrystal8FactImpl18ProcessRequestBaseINS0_14ScatterRequestEE8modifiedEPKc')
```

Please help me to check if I didn't use the commands correctly or should I need to modify some of them? Thx!

**Comment by XuShuqi7** [comment]
Hi @tkittel, 

I replaced SHARED by MODULE in the CMakeLists.txt file, deleted the previous folders, and reran all the commands, but I still got exactly the same error:

```
Traceback (most recent call last):
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/bin/nctool", line 1037, in <module>
    main()
    ~~~~^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/bin/nctool", line 913, in main
    NC.browsePlugins(dump=True)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/plugins.py", line 41, in browsePlugins
    l=_get_raw_cfcts()['ncrystal_get_pluginlist']()
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/_chooks.py", line 789, in ncrystal_get_pluginlist
    _raw_getpluginlist(n,ctypes.byref(l))
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/_chooks.py", line 203, in fcte
    _raise_err()
    ~~~~~~~~~~^^
  File "/Users/shuqixu/opt/miniconda3/envs/ncrystal-extinction/share/NCrystal/python/NCrystal/_chooks.py", line 175, in _raise_err
    raise e
NCrystal.exceptions.NCDataLoadError: Could not load shared library: /Users/shuqixu/Downloads/My_C++/ncrystal_test_plugin/CrysExtn_inst/lib/libNCPlugin_CrysExtn.so (error was: dlopen(/Users/shuqixu/Downloads/My_C++/ncrystal_test_plugin/CrysExtn_inst/lib/libNCPlugin_CrysExtn.so, 0x0006): weak-def symbol not found '__ZNK8NCrystal8FactImpl18ProcessRequestBaseINS0_14ScatterRequestEE8modifiedEPKc')
```

**Comment by tkittel** [comment]
And you are in conda with a conda-installed NCrystal?

**Comment by XuShuqi7** [comment]
Yes, I used the following commands for installing NCrystal:

```
conda create -n ncrystal-extinction -y -c conda-forge jupyter numpy scipy matplotlib pip h5py
conda activate ncrystal-extinction
conda install conda-forge::ncrystal
```

Then followed by the previously listed commands.

**Comment by tkittel** [comment]
Could you try to also install the conda-forge compilers and cmake packages, and then deactivate + activate your environment? And then try again of course.

**Comment by XuShuqi7** [comment]
Yes, I ran 

```
conda install -c conda-forge compilers
conda install -c conda-forge cmake 
```

and deactivate and activate the env, and reran all the process including reinstalling NCrystal, but I still got exactly the same error message.

**Comment by XuShuqi7** [comment]
I used otool to look at the shared libraries used, and I got 

```
/Users/shuqixu/Downloads/My_C++/ncrystal_test_plugin/CrysExtn_inst/lib/libNCPlugin_CrysExtn.so:
	@rpath/libNCrystal.3.dylib (compatibility version 3.0.0, current version 3.9.7)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1351.0.0)
```

**Comment by tkittel** [comment]
Sure, but I meant that you either have to investigate and find the solution, or wait.

**Comment by tkittel** [comment]
Also, please do not comment more on this closed issue. Put comments on #193.

**Comment by XuShuqi7** [comment]
OK. Since we always has a backup solution for including the plugin, we can address this issue later. Thanks a lot for the discussion :-)
